
CORE_INCLUDE_PATH=$(SHOTODOL_HOME)/core/
LIB_INCLUDE_PATH=$(SHOTODOL_HOME)/libs/
INCLUDES+=-Iinclude
INCLUDES+=-I$(CORE_INCLUDE_PATH)/base/include
INCLUDES+=-I$(CORE_INCLUDE_PATH)/io/include
INCLUDES+=-I$(LIB_INCLUDE_PATH)/str_arms/include
INCLUDES+=-I$(LIB_INCLUDE_PATH)/iostream/include
INCLUDES+=-I$(LIB_INCLUDE_PATH)/propeller/include
